# fly.toml app configuration file generated for microposts-hkprj-home on 2025-07-08T00:03:19+09:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'microposts-hkprj-home'
primary_region = 'ams'
console_command = 'php /var/www/html/artisan tinker'

[build]
  [build.args]
    NODE_VERSION = '18'
    PHP_VERSION = '8.3'
    VITE_APP_URL = 'https://microposts-hkprj-home.fly.dev'

[env]
  APP_ENV = 'production'
  APP_URL = 'https://microposts-hkprj-home.fly.dev'
  VITE_APP_URL = 'https://microposts-hkprj-home.fly.dev'
  LOG_CHANNEL = 'stderr'
  LOG_LEVEL = 'info'
  LOG_STDERR_FORMATTER = 'Monolog\Formatter\JsonFormatter'
  SESSION_DRIVER = 'cookie'
  SESSION_SECURE_COOKIE = 'true'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
